# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.3

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/mfranc/projects/perso/cppCrossPlateformSocketProvider

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/mfranc/projects/perso/cppCrossPlateformSocketProvider

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mfranc/projects/perso/cppCrossPlateformSocketProvider/CMakeFiles /home/mfranc/projects/perso/cppCrossPlateformSocketProvider/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mfranc/projects/perso/cppCrossPlateformSocketProvider/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named cppCrossPlateformSocketProvider

# Build rule for target.
cppCrossPlateformSocketProvider: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cppCrossPlateformSocketProvider
.PHONY : cppCrossPlateformSocketProvider

# fast build rule for target.
cppCrossPlateformSocketProvider/fast:
	$(MAKE) -f CMakeFiles/cppCrossPlateformSocketProvider.dir/build.make CMakeFiles/cppCrossPlateformSocketProvider.dir/build
.PHONY : cppCrossPlateformSocketProvider/fast

SocketClientProvider.o: SocketClientProvider.cpp.o

.PHONY : SocketClientProvider.o

# target to build an object file
SocketClientProvider.cpp.o:
	$(MAKE) -f CMakeFiles/cppCrossPlateformSocketProvider.dir/build.make CMakeFiles/cppCrossPlateformSocketProvider.dir/SocketClientProvider.cpp.o
.PHONY : SocketClientProvider.cpp.o

SocketClientProvider.i: SocketClientProvider.cpp.i

.PHONY : SocketClientProvider.i

# target to preprocess a source file
SocketClientProvider.cpp.i:
	$(MAKE) -f CMakeFiles/cppCrossPlateformSocketProvider.dir/build.make CMakeFiles/cppCrossPlateformSocketProvider.dir/SocketClientProvider.cpp.i
.PHONY : SocketClientProvider.cpp.i

SocketClientProvider.s: SocketClientProvider.cpp.s

.PHONY : SocketClientProvider.s

# target to generate assembly for a file
SocketClientProvider.cpp.s:
	$(MAKE) -f CMakeFiles/cppCrossPlateformSocketProvider.dir/build.make CMakeFiles/cppCrossPlateformSocketProvider.dir/SocketClientProvider.cpp.s
.PHONY : SocketClientProvider.cpp.s

SocketProvider.o: SocketProvider.cpp.o

.PHONY : SocketProvider.o

# target to build an object file
SocketProvider.cpp.o:
	$(MAKE) -f CMakeFiles/cppCrossPlateformSocketProvider.dir/build.make CMakeFiles/cppCrossPlateformSocketProvider.dir/SocketProvider.cpp.o
.PHONY : SocketProvider.cpp.o

SocketProvider.i: SocketProvider.cpp.i

.PHONY : SocketProvider.i

# target to preprocess a source file
SocketProvider.cpp.i:
	$(MAKE) -f CMakeFiles/cppCrossPlateformSocketProvider.dir/build.make CMakeFiles/cppCrossPlateformSocketProvider.dir/SocketProvider.cpp.i
.PHONY : SocketProvider.cpp.i

SocketProvider.s: SocketProvider.cpp.s

.PHONY : SocketProvider.s

# target to generate assembly for a file
SocketProvider.cpp.s:
	$(MAKE) -f CMakeFiles/cppCrossPlateformSocketProvider.dir/build.make CMakeFiles/cppCrossPlateformSocketProvider.dir/SocketProvider.cpp.s
.PHONY : SocketProvider.cpp.s

SocketServerProvider.o: SocketServerProvider.cpp.o

.PHONY : SocketServerProvider.o

# target to build an object file
SocketServerProvider.cpp.o:
	$(MAKE) -f CMakeFiles/cppCrossPlateformSocketProvider.dir/build.make CMakeFiles/cppCrossPlateformSocketProvider.dir/SocketServerProvider.cpp.o
.PHONY : SocketServerProvider.cpp.o

SocketServerProvider.i: SocketServerProvider.cpp.i

.PHONY : SocketServerProvider.i

# target to preprocess a source file
SocketServerProvider.cpp.i:
	$(MAKE) -f CMakeFiles/cppCrossPlateformSocketProvider.dir/build.make CMakeFiles/cppCrossPlateformSocketProvider.dir/SocketServerProvider.cpp.i
.PHONY : SocketServerProvider.cpp.i

SocketServerProvider.s: SocketServerProvider.cpp.s

.PHONY : SocketServerProvider.s

# target to generate assembly for a file
SocketServerProvider.cpp.s:
	$(MAKE) -f CMakeFiles/cppCrossPlateformSocketProvider.dir/build.make CMakeFiles/cppCrossPlateformSocketProvider.dir/SocketServerProvider.cpp.s
.PHONY : SocketServerProvider.cpp.s

client.o: client.cpp.o

.PHONY : client.o

# target to build an object file
client.cpp.o:
	$(MAKE) -f CMakeFiles/cppCrossPlateformSocketProvider.dir/build.make CMakeFiles/cppCrossPlateformSocketProvider.dir/client.cpp.o
.PHONY : client.cpp.o

client.i: client.cpp.i

.PHONY : client.i

# target to preprocess a source file
client.cpp.i:
	$(MAKE) -f CMakeFiles/cppCrossPlateformSocketProvider.dir/build.make CMakeFiles/cppCrossPlateformSocketProvider.dir/client.cpp.i
.PHONY : client.cpp.i

client.s: client.cpp.s

.PHONY : client.s

# target to generate assembly for a file
client.cpp.s:
	$(MAKE) -f CMakeFiles/cppCrossPlateformSocketProvider.dir/build.make CMakeFiles/cppCrossPlateformSocketProvider.dir/client.cpp.s
.PHONY : client.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... cppCrossPlateformSocketProvider"
	@echo "... SocketClientProvider.o"
	@echo "... SocketClientProvider.i"
	@echo "... SocketClientProvider.s"
	@echo "... SocketProvider.o"
	@echo "... SocketProvider.i"
	@echo "... SocketProvider.s"
	@echo "... SocketServerProvider.o"
	@echo "... SocketServerProvider.i"
	@echo "... SocketServerProvider.s"
	@echo "... client.o"
	@echo "... client.i"
	@echo "... client.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

